name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: internet-truck-stop
  GAR_LOCATION: us-central1
  REPOSITORY: internet-truck-stop-repo
  IMAGE: internet-truck-stop
  CLUSTER_NAME: internet-truck-stop-cluster
  CLUSTER_LOCATION: us-central1

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest ./nodejs-app

    - name: Push Docker image
      run: |
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
          --region ${{ env.CLUSTER_LOCATION }} \
          --project ${{ env.PROJECT_ID }}

    - name: Deploy with Helm
      run: |
        helm upgrade --install internet-truck-stop ./helm/internet-truck-stop \
          --set image.repository=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }} \
          --set image.tag=latest
