apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: internet-truck-stop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: internet-truck-stop
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
