name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: internet-truck-stop
  GAR_LOCATION: us-central1
  REPOSITORY: internet-truck-stop-repo
  IMAGE: internet-truck-stop
  CLUSTER_NAME: internet-truck-stop-cluster
  CLUSTER_LOCATION: us-central1

jobs:
  build-and-deploy:
    name: Build and Deploy Docker image to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA nodejs-app
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials $CLUSTER_NAME --region $CLUSTER_LOCATION --project $PROJECT_ID

      - name: Deploy to GKE with kubectl
        run: |
          kubectl set image deployment/$IMAGE $IMAGE=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
